version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - TZ=Europe/Istanbul
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    environment:
      - TZ=Europe/Istanbul
    depends_on:
      web:
        condition: service_healthy
    restart: always

networks:
  default:
    driver: bridge
