name: CI - Build & Push to Harbor & Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Configure Docker for Insecure Harbor Registry
        run: |
          echo '{ "insecure-registries": ["${{ secrets.HARBOR_URL }}"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
 
      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login http://${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
 
      - name: Build Docker Image
        run: docker build -t ${{ secrets.HARBOR_URL }}/${{ secrets.IMAGE_WEB }}:latest .
 
      - name: Push Docker Image
        run: docker push ${{ secrets.HARBOR_URL }}/${{ secrets.IMAGE_WEB }}:latest
 
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
 
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              insecure-skip-tls-verify: true
              server: ${{ secrets.K8S_API }}
            name: prod-cluster
          contexts:
          - context:
              cluster: prod-cluster
              user: gitops-user
            name: default
          current-context: default
          users:
          - name: gitops-user
            user:
              token: ${{ secrets.K8S_TOKEN }}
          " > $HOME/.kube/config
 
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment domainchecker
